# Generated by Django 5.2 on 2025-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
